defmodule Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:my_res, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name1, :text, null: false)
      add(:name2, :text, null: false)
      add(:name1_ci, :citext, null: false)
      add(:name2_ci, :citext, null: false)
      add(:dummy, :citext)
    end
  end

  def down do
    drop(table(:my_res))
  end
end
